eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    # http  rabbitmq方式可以不需要
#    base-url: http://127.0.0.1:9411/
    #发送的队列名称，默认zipkin，正常情况不要修改因为zipkin-server默认监控队列也是zipkin
#    rabbitmq:
#        queue: zipkin
    enabled: true
    #日志发送队列类型
    sender:
      type: RABBIT
#  rabbitmq:
#    addresses: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  cloud:
    gateway:
#      discovery:      #方式一、是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
#        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
#          enabled: true
      routes:  #方式二 使用lb负载均衡加载
      - id: USERSERVICE
        uri: lb://USER-SERVICE:8762
        predicates:
          - Path=/userapi/**
        filters:
          - StripPrefix=1
#      routes:  #方式三 直接使用 域名地址
#      - id: USERSERVICE
#        uri: http://localhost:8762
#        predicates:
#          - Path=/userapi/**
#        filters:
#          - StripPrefix=1
logging:
  level:
    root: info