server:
  port: 8769

#local
#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native
#  application:
#    name: config-server

# remote git
spring:
  cloud:
    config:
      server:
        git:
          # 仓库地址
          uri: https://github.com/bjlhx15/spring-cloud-base.git
          # 相对路径
          searchPaths: spring-cloud-config-study/respo
          username: bjlhx15@163.com
          password:
      label: master
  application:
    name: config-server