server:
  port: 5000
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    # http  方式
    base-url: http://localhost:9411/
    sender:
      type: WEB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
  cloud:
    gateway:
#      discovery:      #方式一、是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
#        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
#          enabled: true
      routes:  #方式二 使用lb负载均衡加载
      - id: user-service
        uri: lb://USER-SERVICE:8762
        predicates:
          - Path=/userapi/**
        filters:
          - StripPrefix=1
      - id: blog-service
        uri: lb://BLOG-SERVICE:8763
        predicates:
          - Path=/blogapi/**
        filters:
          - StripPrefix=1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

eureka:
  instance:
  # 方式二、使用Eureka提交凭据
    metadata-map:
      user.name: admin
      user.password: 123456