server:
  port: 9996
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:53306/sys-log?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    # http  方式
    base-url: http://localhost:9411/
    sender:
      type: WEB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /

