server:
  port: 8766
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: default
  appConfig: user-service , blog-service
  clusterNameExpression: new String("default")

management:
  security:
    enabled: false
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
management.endpoint.bus-refresh.enabled: true
management.endpoints.web.exposure.include: bus-refresh