spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:53306/sys-user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    # http  方式
    base-url: http://localhost:9411/
    sender:
      type: WEB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
#  security:
#    user:
#      name: admin
#      password: 123456
#management.endpoint.bus-refresh.enabled: true
#management.endpoints.web.exposure.include: bus-refresh
server:
  port: 9999
#logging.level.root: debug

#eureka:
#  instance:
#  # 方式二、使用Eureka提交凭据
#    metadata-map:
#      user.name: ${spring.security.user.name}
#      user.password: ${spring.security.user.password}

