eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server
#spring.sleuth.sampler.percentage: 1.0
# zipkin server2.0版本 需要添加以下
management:
  metrics:
    web:
      server:
        auto-time-requests: false