logging:
  file: "logs/boot-admin-sample.log"
server:
  port: 5000

spring:
  application:
    name: service-admin
  # 外面登录
  security:
    user:
      name: admin
      password: 1234
  #  boot:
  #    admin:
  #      client:
  #        url: http://localhost:5000
  #        #  方式一 使用SBA客户端提交凭据
  #        instance:
  #          metadata:
  #            user.name: ${spring.security.user.name}
  #            user.password: ${spring.security.user.password}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
  # 方式二、使用Eureka提交凭据
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

