spring:
  application:
    name: service-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:53306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5000
  servlet:
    context-path: /uaa
security:
  oauth2:
    resource:
      filter-order: 3
#  basic:
#    enabled: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#management:
#  security:
#    enabled: false
#logging:
#  level:
#    root: trace



