# remote git
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/bjlhx
#          searchPaths: backend/repo
#          username: bjlhx15@163.com
#          password:
#      label: master

# ---native
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  application:
    name: config-server

# port
server:
  port: 8769

management:
  security:
    enabled: false